name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t ghcr.io/${{ github.repository_owner }}/github-actions-cicd:latest .

    - name: Login to GitHub Container Registry
      run: echo ${{ secrets.GH_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

    - name: Push Docker Image
      run: docker push ghcr.io/${{ github.repository_owner }}/github-actions-cicd:latest

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@<EC2-IP> 'bash -s' < deploy.sh
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_KEY }}
